const paths = {
  phone:
    '<path d="M6 3H3a1 1 0 0 0-1 1c0 10 8 18 18 18a1 1 0 0 0 1-1v-3l-5-2-2 2c-4-2-6-4-8-8l2-2z"/>',
  mic: '<rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',
  speaker: '<path d="M3 9h4l5-4v14l-5-4H3zM16 8q5 4 0 8M19 4q9 8 0 16"/>',
  message:
    '<path d="M21 11c0 5-4 8-9 8H7l-5 3 1-6a8 8 0 0 1-1-5c0-5 4-8 10-8s9 3 9 8z"/>',
  grid: '<circle cx="5" cy="5" r="1"/><circle cx="12" cy="5" r="1"/><circle cx="19" cy="5" r="1"/><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="19" r="1"/><circle cx="12" cy="19" r="1"/><circle cx="19" cy="19" r="1"/>',
};
export const icon = (name) =>
  `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name] || paths.phone}</svg>`;
export function iphoneShell() {
  return `<div class="voice-room"><div class="iphone-hardware"><i class="side-button side-one"></i><i class="side-button side-two"></i><i class="side-button side-three"></i><section class="farmer-phone" data-state="waiting"><div class="dynamic-island"><i></i></div><div class="phone-top"><span id="device-time">9:41</span><span class="status-icons">▂▄▆ <span>5G</span> ▰</span></div><button id="message-notification" class="message-notification" hidden><span class="messages-app">${icon("message")}</span><span><small>MESSAGES <em>now</em></small><b>AgriSell</b><span id="notification-text"></span></span></button><div id="call-screen"><div class="contact-photo">अ</div><p class="eyebrow">AgriSell • Farm assistant</p><h1>AgriSell</h1><p id="voice-status" role="status">Available for calls</p><p id="voice-caption">Market advice. A familiar voice.</p><div class="mic-meter" aria-label="Microphone level"><i id="mic-level"></i></div><p id="capture-status" aria-live="polite"></p><p id="stock-saved" aria-live="polite"></p><div class="ios-call-grid"><button id="speaker-call">${icon("speaker")}<small>audio</small></button><button id="mute-call" hidden>${icon("mic")}<small>mute</small></button><button id="show-transcript">${icon("message")}<small>transcript</small></button></div><div class="phone-actions"><button id="decline-call" hidden>${icon("phone")}<small>Decline</small></button><button id="answer-call" disabled>${icon("phone")}<small>Accept</small></button><button id="end-call" hidden>${icon("phone")}<small>End</small></button></div><details id="transcript-panel"><summary>Conversation</summary><p id="live-transcript"></p></details><button id="open-messages" class="open-messages">${icon("message")} Messages</button></div><section id="messages-screen" hidden><header class="messages-header"><button id="back-call" aria-label="Back to call">‹</button><div><div class="message-avatar">अ</div><b>AgriSell <span>›</span></b></div></header><div class="message-thread"><p class="thread-label">Messages · AgriSell<br><span id="message-date"></span></p><div id="message-empty">Message AgriSell about your stock, market prices or weather. Your call summary will appear here too.</div><div id="receipt-bubble" class="receipt-bubble" hidden></div><div id="receipt-sources" class="receipt-sources"></div><div id="chat-messages" aria-live="polite"></div><p id="message-error" role="status"></p></div><form id="message-form" class="message-compose"><div><input id="message-input" aria-label="Message AgriSell" placeholder="Message" maxlength="1500" autocomplete="off"><button id="send-message" type="submit" aria-label="Send message">↑</button></div></form></section><div class="home-indicator"></div></section></div></div>`;
}
