import './styles.css';

const farmers = [
  { name: 'Ramesh Kumar', crop: 'Tomato', stock: '1,000 kg', place: 'Nashik', language: 'Marathi', action: 'WAIT', price: '₹26–27', change: '+₹2.80', time: '12 min ago', color: 'amber' },
  { name: 'Sunita Patil', crop: 'Onion', stock: '2,400 kg', place: 'Lasalgaon', language: 'Marathi', action: 'SELL NOW', price: '₹21', change: 'stable', time: '34 min ago', color: 'green' },
  { name: 'Mahesh Jadhav', crop: 'Tomato', stock: '650 kg', place: 'Dindori', language: 'Hindi', action: 'OTHER MANDI', price: '₹25.50', change: '+₹1.50', time: '1 hr ago', color: 'blue' },
  { name: 'Asha Shinde', crop: 'Grapes', stock: '800 kg', place: 'Sinnar', language: 'Marathi', action: 'WAIT', price: '₹84–88', change: '+₹4.20', time: '2 hrs ago', color: 'amber' },
];

const row = f => `<tr><td><div class="farmer"><span class="avatar">${f.name.split(' ').map(x=>x[0]).join('')}</span><span><strong>${f.name}</strong><small>${f.place} · ${f.language}</small></span></div></td><td>${f.crop}<small>${f.stock}</small></td><td><span class="pill ${f.color}">${f.action}</span></td><td><strong>${f.price}</strong><small>${f.change} expected</small></td><td class="muted">${f.time}</td><td><button class="more">···</button></td></tr>`;

document.querySelector('#app').innerHTML = `<div class="shell"><aside><div class="brand"><div class="logo">✦</div><div><b>AgriSell</b><span>FIELD DESK</span></div></div><div class="workspace"><small>WORKSPACE</small><b>Nashik FPO <i>⌄</i></b></div><nav><a class="active"><span>◉</span> Overview</a><a><span>♧</span> Farmers <em>28</em></a><a><span>◌</span> Recommendations <em class="hot">4</em></a><a><span>⌁</span> Calls</a></nav><div class="aside-foot"><div class="signal"><span></span><div><b>Data is live</b><small>Last synced 8 min ago</small></div></div><div class="user"><span class="avatar">AK</span><div><b>Anita Kulkarni</b><small>Field officer</small></div><span>⌄</span></div></div></aside><main><header><div><p class="eyebrow">THURSDAY · 03 SEPTEMBER 2026</p><h1>Good morning, Anita <span>✳</span></h1><p class="subtitle">Here’s what needs your attention across the fields today.</p></div><button class="primary" id="addBtn">＋ Add farmer</button></header><section class="hero"><div><p class="eyebrow light">TODAY’S FIELD SIGNAL</p><h2>4 farmers have a<br/><i>decision to make.</i></h2><p>Market movement is creating meaningful opportunities. Review recommendations before the morning collection window.</p><button class="hero-btn" id="reviewBtn">Review recommendations <span>→</span></button></div><div class="sun">☼<small>28°<br/>Nashik</small></div><div class="orbit orbit1"></div><div class="orbit orbit2"></div></section><div class="stats"><div><span>FARMERS ON FILE</span><strong>28</strong><small>+3 this month</small></div><div><span>ACTIVE CROP RECORDS</span><strong>19</strong><small>Across 4 crops</small></div><div><span>CALLS DELIVERED</span><strong>86%</strong><small>↑ 8% from last week</small></div><div><span>EST. VALUE FOUND</span><strong>₹18.4k</strong><small>This week’s opportunity</small></div></div><section class="section-head"><div><p class="eyebrow">LIVE WORK QUEUE</p><h2>Recommendations</h2></div><div class="filters"><button class="filter active">All <b>4</b></button><button class="filter">Needs review <b>2</b></button><button class="filter">Calls pending <b>1</b></button></div></section><div class="table-wrap"><table><thead><tr><th>FARMER</th><th>CROP & STOCK</th><th>RECOMMENDATION</th><th>EXPECTED PRICE</th><th>UPDATED</th><th></th></tr></thead><tbody>${farmers.map(row).join('')}</tbody></table></div><p class="footnote">Prices are forecasts based on mandi arrivals, weather and recent trends. Always confirm availability with the farmer.</p></main></div><div class="toast" id="toast">Farmer form is ready for the next step.</div>`;

const toast = document.querySelector('#toast');
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
document.querySelector('#addBtn').onclick = () => showToast('Farmer onboarding will be connected here.');
document.querySelector('#reviewBtn').onclick = () => document.querySelector('.table-wrap').scrollIntoView({ behavior: 'smooth' });
document.querySelectorAll('.filter').forEach(button => button.onclick = () => { document.querySelectorAll('.filter').forEach(x => x.classList.remove('active')); button.classList.add('active'); showToast(`${button.textContent.trim()} recommendations selected.`); });
